language: node_js
node_js: lts/*
install:
  - yarn install # npm ci
jobs:
  include:
    - stage: 'build docs'
      script:
        - npm run docs:build
    - stage: 'deploy docs'
      script: skip
      deploy:
        provider: pages
        # skip_cleanup: true
        local_dir: docs/.vuepress/dist
        github_token: $GITHUB_TOKEN # A token generated on GitHub allowing Travis to push code on you repository. Set in the Travis settings page of your repository, as a secure variable
        keep_history: true
        on:
          branch: master
